download_cedict:
	curl -o cedict.txt.gz https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.txt.gz && gzip -d cedict.txt.gz

download_subtlex:
	wget http://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexch/subtlexchwf.zip && unzip subtlexchwf.zip
