// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RR from "../utils/RR.bs.js";
import * as $$Array from "../utils/Array.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function getRandomHanzi(count) {
  return $$Array.makeBy(count, (function (_i) {
                  return String.fromCharCode(Js_math.random_int(19968, 40960));
                })).join("");
}

function getHanziLines(count) {
  return $$Array.makeBy(count, getRandomHanzi);
}

function HanziPyramid(Props) {
  var match = React.useState(function () {
        return String(8);
      });
  var setCount = match[1];
  var count = match[0];
  var match$1 = React.useState(function () {
        return $$Array.makeBy(8, getRandomHanzi);
      });
  var setLines = match$1[1];
  var generate = function (param) {
    return Curry._1(setLines, (function (param) {
                  var count$1 = Belt_Option.getWithDefault(Pervasives.int_of_string_opt(count), 1);
                  return $$Array.makeBy(count$1, getRandomHanzi);
                }));
  };
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "text-4xl"
                }, RR.s("Hanzi pyramid")), React.createElement("div", undefined, React.createElement("input", {
                      className: "border-black",
                      placeholder: "Number of characters",
                      type: "number",
                      value: count,
                      onKeyPress: (function (evt) {
                          if (evt.key === "Enter") {
                            return generate(undefined);
                          }
                          
                        }),
                      onChange: (function (evt) {
                          return Curry._1(setCount, (function (param) {
                                        return evt.target.value;
                                      }));
                        })
                    }), React.createElement("button", {
                      className: "bg-blue-500 hover:bg-blue-700 text-white rounded p-1",
                      onClick: (function (param) {
                          return generate(undefined);
                        })
                    }, RR.s("Generate"))), $$Array.mapWithIndex(match$1[0], (function (i, line) {
                    return React.createElement("p", {
                                key: String(i),
                                className: "text-3xl"
                              }, RR.s(line));
                  })));
}

var make = HanziPyramid;

export {
  getRandomHanzi ,
  getHanziLines ,
  make ,
  
}
/* react Not a pure module */
