// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H1 from "../widgets/H1.bs.js";
import * as RR from "../utils/RR.bs.js";
import * as React from "react";

function NotFound(Props) {
  return React.createElement("div", undefined, React.createElement(H1.make, {
                  children: RR.s("Not found")
                }), React.createElement("a", {
                  href: "/"
                }, RR.s("要不回到主页？")));
}

var make = NotFound;

export {
  make ,
  
}
/* H1 Not a pure module */
