// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RR from "../utils/RR.bs.js";
import * as $$Array from "../utils/Array.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Button from "../widgets/Button.bs.js";
import * as Select from "../widgets/Select.bs.js";
import * as SpeechSynthesis from "../utils/SpeechSynthesis.bs.js";

var litany = "I must not fear.\nFear is the mind-killer.\nFear is the little-death that brings total obliteration.\nI will face my fear.\nI will permit it to pass over me and through me.\nAnd when it has gone past, I will turn the inner eye to see its path.\nWhere the fear has gone there will be nothing. Only I will remain.";

function SpeechSynthesisDemo(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setVoices = match[1];
  var match$1 = React.useState(function () {
        
      });
  var setVoice = match$1[1];
  var voice = match$1[0];
  var match$2 = React.useState(function () {
        return litany;
      });
  var setText = match$2[1];
  var text = match$2[0];
  React.useEffect((function () {
          SpeechSynthesis.onVoicesReady(function (voices) {
                Curry._1(setVoices, (function (param) {
                        return voices;
                      }));
                return Curry._1(setVoice, (function (param) {
                              return $$Array.get(voices, 0);
                            }));
              });
          
        }), []);
  return React.createElement("div", undefined, voice !== undefined ? React.createElement(React.Fragment, undefined, React.createElement(Select.make, {
                        value: voice,
                        isEqual: (function (a, b) {
                            return a.name === b.name;
                          }),
                        onChange: (function (v) {
                            console.log(v);
                            return Curry._1(setVoice, (function (param) {
                                          return v;
                                        }));
                          }),
                        children: match[0].map(function (voice) {
                              return React.createElement(Select.Item.make, {
                                          label: voice.name + " (" + voice.lang + ")",
                                          value: voice,
                                          key: voice.name
                                        });
                            })
                      }), React.createElement(Button.make, {
                        onClick: (function (param) {
                            speechSynthesis.cancel();
                            var utterance = new SpeechSynthesisUtterance(text);
                            utterance.voice = voice;
                            speechSynthesis.speak(utterance);
                            
                          }),
                        children: RR.s("Speak")
                      })) : RR.s("No voices"), React.createElement("div", undefined, React.createElement("textarea", {
                      cols: 60,
                      rows: 7,
                      value: text,
                      onChange: (function (evt) {
                          return Curry._1(setText, (function (param) {
                                        return evt.currentTarget.value;
                                      }));
                        })
                    })));
}

var Speech;

var make = SpeechSynthesisDemo;

export {
  Speech ,
  litany ,
  make ,
  
}
/* react Not a pure module */
