// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H1 from "../widgets/H1.bs.js";
import * as RR from "../utils/RR.bs.js";
import * as $$Array from "../utils/Array.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Button from "../widgets/Button.bs.js";
import * as Select from "../widgets/Select.bs.js";
import * as SpeechSynthesis from "../utils/SpeechSynthesis.bs.js";

var litany = "I must not fear.\nFear is the mind-killer.\nFear is the little-death that brings total obliteration.\nI will face my fear.\nI will permit it to pass over me and through me.\nAnd when it has gone past, I will turn the inner eye to see its path.\nWhere the fear has gone there will be nothing. Only I will remain.";

function SpeechSynthesisDemo(Props) {
  var match = RR.useStateValue([]);
  var setVoices = match[1];
  var match$1 = RR.useStateValue(undefined);
  var setVoice = match$1[1];
  var voice = match$1[0];
  var match$2 = RR.useStateValue(litany);
  var setText = match$2[1];
  var text = match$2[0];
  React.useEffect((function () {
          SpeechSynthesis.onVoicesReady(function (voices) {
                Curry._1(setVoices, voices);
                return Curry._1(setVoice, $$Array.get(voices, 0));
              });
          
        }), []);
  return React.createElement("div", {
              className: "space-y-4"
            }, React.createElement(H1.make, {
                  children: RR.s("Speech Synthesis")
                }), voice !== undefined ? React.createElement("div", {
                    className: "flex flex-row space-x-2"
                  }, React.createElement(Select.make, {
                        value: voice,
                        isEqual: (function (a, b) {
                            return a.name === b.name;
                          }),
                        onChange: (function (v) {
                            console.log(v);
                            return Curry._1(setVoice, v);
                          }),
                        children: match[0].map(function (voice) {
                              return React.createElement(Select.Item.make, {
                                          label: voice.name + " (" + voice.lang + ")",
                                          value: voice,
                                          key: voice.name
                                        });
                            })
                      }), React.createElement(Button.make, {
                        onClick: (function (param) {
                            speechSynthesis.cancel();
                            var utterance = new SpeechSynthesisUtterance(text);
                            utterance.voice = voice;
                            speechSynthesis.speak(utterance);
                            
                          }),
                        children: RR.s("Speak")
                      }), React.createElement(Button.make, {
                        onClick: (function (param) {
                            speechSynthesis.cancel();
                            
                          }),
                        children: RR.s("Stop")
                      })) : RR.s("No voices"), React.createElement("div", undefined, React.createElement("textarea", {
                      cols: 80,
                      rows: 7,
                      value: text,
                      onChange: (function (evt) {
                          return Curry._1(setText, evt.currentTarget.value);
                        })
                    })));
}

var Speech;

var litanyZh = "我絕不能害怕\n恐懼會扼殺思維能力\n是潛伏的死神\n會徹底毀滅一個人\n我要容忍它\n讓他掠過我的心頭\n穿越我的心身\n當這一切過去之後\n我將睜開心靈深處的眼神\n審視它的軌跡\n恐懼如風\n風過無痕\n唯有我依然屹立";

var make = SpeechSynthesisDemo;

export {
  Speech ,
  litany ,
  litanyZh ,
  make ,
  
}
/* H1 Not a pure module */
