// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RR from "../utils/RR.bs.js";
import * as React from "react";

var voices = window.speechSynthesis.getVoices();

function SpeechSynthesis(Props) {
  return React.createElement("div", undefined, voices.map(function (voice) {
                  return React.createElement("div", {
                              key: voice.name
                            }, RR.s(voice.name + " (" + voice.lang + ")"));
                }));
}

var make = SpeechSynthesis;

export {
  voices ,
  make ,
  
}
/* voices Not a pure module */
