// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H1 from "../widgets/H1.bs.js";
import * as RR from "../utils/RR.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Select from "../widgets/Select.bs.js";

function fruitToJs(param) {
  return param + 0 | 0;
}

function fruitFromJs(param) {
  if (param <= 4 && 0 <= param) {
    return param - 0 | 0;
  }
  
}

function WidgetsDemo(Props) {
  var match = React.useState(function () {
        return /* Avocado */0;
      });
  var setValue = match[1];
  var value = match[0];
  return React.createElement("div", {
              className: "space-y-4"
            }, React.createElement(H1.make, {
                  children: RR.s("Widgets Demo")
                }), React.createElement("div", undefined, React.createElement("div", {
                      className: "font-bold"
                    }, RR.s("Select")), React.createElement("div", {
                      className: "flex flex-row items-center"
                    }, React.createElement("div", {
                          className: "mr-6"
                        }, React.createElement("span", {
                              className: "font-extralight"
                            }, RR.s("Current value: ")), RR.s(String(value + 0 | 0))), React.createElement(Select.make, {
                          value: value,
                          isEqual: (function (a, b) {
                              return a === b;
                            }),
                          onChange: (function (v) {
                              return Curry._1(setValue, (function (param) {
                                            return v;
                                          }));
                            }),
                          children: null
                        }, React.createElement(Select.Item.make, {
                              label: "Avocado",
                              value: /* Avocado */0
                            }), React.createElement(Select.Item.make, {
                              label: "Banana",
                              value: /* Banana */1
                            }), React.createElement(Select.Item.make, {
                              label: "Coconut",
                              value: /* Coconut */2
                            }), React.createElement(Select.Item.make, {
                              label: "Orange",
                              value: /* Orange */3
                            }), React.createElement(Select.Item.make, {
                              label: "Watermelon",
                              value: /* Watermelon */4
                            })))));
}

var make = WidgetsDemo;

export {
  fruitToJs ,
  fruitFromJs ,
  make ,
  
}
/* H1 Not a pure module */
