// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "@rescript/react/src/React.bs.js";

function s(prim) {
  return prim;
}

var Ref = React.Ref;

var Children = React.Children;

var Context = React.Context;

var Fragment = React.Fragment;

var StrictMode = React.StrictMode;

var Suspense = React.Suspense;

var Experimental = React.Experimental;

var Uncurried = React.Uncurried;

export {
  Ref ,
  Children ,
  Context ,
  Fragment ,
  StrictMode ,
  Suspense ,
  Experimental ,
  Uncurried ,
  s ,
  
}
/* No side effect */
