// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "@rescript/react/src/React.bs.js";
import * as React$1 from "react";

function s(prim) {
  return prim;
}

function useStateValue(initial) {
  return React$1.useReducer((function (_ignored, newState) {
                return newState;
              }), initial);
}

var Ref = React.Ref;

var Children = React.Children;

var Context = React.Context;

var Fragment = React.Fragment;

var StrictMode = React.StrictMode;

var Suspense = React.Suspense;

var Experimental = React.Experimental;

var Uncurried = React.Uncurried;

export {
  Ref ,
  Children ,
  Context ,
  Fragment ,
  StrictMode ,
  Suspense ,
  Experimental ,
  Uncurried ,
  s ,
  useStateValue ,
  
}
/* react Not a pure module */
