// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";

function equal(s1, s2) {
  return s1 === s2;
}

var compare = Caml.caml_string_compare;

export {
  equal ,
  compare ,
  
}
/* No side effect */
