// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Main from "./Main.bs.js";
import * as Route from "./Route.bs.js";
import * as React from "react";
import * as NotFound from "./pages/NotFound.bs.js";
import * as WidgetsDemo from "./pages/WidgetsDemo.bs.js";
import * as HanziPyramid from "./pages/HanziPyramid.bs.js";
import * as SpeechSynthesis from "./pages/SpeechSynthesis.bs.js";
import * as SpeechRecognition from "./pages/SpeechRecognition.bs.js";

function App(Props) {
  var route = Route.useRoute(undefined);
  var tmp;
  switch (route) {
    case /* Main */0 :
        tmp = React.createElement(Main.make, {});
        break;
    case /* HanziPyramid */1 :
        tmp = React.createElement(HanziPyramid.make, {});
        break;
    case /* SpeechRecognition */2 :
        tmp = React.createElement(SpeechRecognition.make, {});
        break;
    case /* SpeechSynthesis */3 :
        tmp = React.createElement(SpeechSynthesis.make, {});
        break;
    case /* WidgetsDemo */4 :
        tmp = React.createElement(WidgetsDemo.make, {});
        break;
    case /* NotFound */5 :
        tmp = React.createElement(NotFound.make, {});
        break;
    
  }
  return React.createElement("div", {
              className: "p-4"
            }, tmp);
}

var make = App;

export {
  make ,
  
}
/* Main Not a pure module */
