// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", {
              className: "p-4"
            }, React.createElement("h1", {
                  className: "text-4xl"
                }, "Feihong's RescriptReact Quickstart"), React.createElement("p", undefined, "欢迎你来看我的示范！"));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
