// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var elem = document.querySelector("#root");

if (!(elem == null)) {
  ReactDom.render(React.createElement(React.StrictMode, {
            children: React.createElement(App.make, {})
          }), elem);
}

export {
  
}
/* elem Not a pure module */
