// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RR from "./utils/RR.bs.js";
import * as Route from "./Route.bs.js";
import * as React from "react";

function Main$Link(Props) {
  var route = Props.route;
  var children = Props.children;
  var path = Route.getPath(route);
  return React.createElement("li", undefined, React.createElement("a", {
                  href: path
                }, children));
}

var Link = {
  make: Main$Link
};

function Main(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "text-4xl"
                }, RR.s("Feihong's RescriptReact Quickstart")), React.createElement("p", {
                  className: "mb-4"
                }, RR.s("欢迎你来看我的示范！")), React.createElement("ul", {
                  className: "list-inside list-disc"
                }, React.createElement(Main$Link, {
                      route: /* HanziPyramid */1,
                      children: RR.s("Hanzi pyramid")
                    }), React.createElement(Main$Link, {
                      route: /* WidgetsDemo */4,
                      children: RR.s("Widgets demo")
                    }), React.createElement(Main$Link, {
                      route: /* SpeechRecognition */2,
                      children: RR.s("Speech recognition")
                    }), React.createElement(Main$Link, {
                      route: /* SpeechSynthesis */3,
                      children: RR.s("Speech synthesis")
                    }), React.createElement("li", undefined, RR.s("Time talk")), React.createElement("li", undefined, RR.s("Music player")), React.createElement("li", undefined, RR.s("Vocab quiz"))));
}

var make = Main;

export {
  Link ,
  make ,
  
}
/* Route Not a pure module */
