// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RR from "./utils/RR.bs.js";
import * as React from "react";

function NotFound(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "text-6xl"
                }, RR.s("Not found")), React.createElement("a", {
                  href: "/"
                }, RR.s("要不回到主页？")));
}

var make = NotFound;

export {
  make ,
  
}
/* react Not a pure module */
