// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function useRoute(param) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return /* Main */0;
  }
  switch (match.hd) {
    case "hanzi-pyramid" :
        if (match.tl) {
          return /* NotFound */4;
        } else {
          return /* HanziPyramid */1;
        }
    case "speech-recognition" :
        if (match.tl) {
          return /* NotFound */4;
        } else {
          return /* SpeechRecognition */2;
        }
    case "speech-synthesis" :
        if (match.tl) {
          return /* NotFound */4;
        } else {
          return /* SpeechSynthesis */3;
        }
    default:
      return /* NotFound */4;
  }
}

function getPath(t) {
  switch (t) {
    case /* HanziPyramid */1 :
        return "hanzi-pyramid";
    case /* SpeechRecognition */2 :
        return "speech-recognition";
    case /* SpeechSynthesis */3 :
        return "speech-synthesis";
    case /* Main */0 :
    case /* NotFound */4 :
        return "";
    
  }
}

export {
  useRoute ,
  getPath ,
  
}
/* RescriptReactRouter Not a pure module */
