// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function useRoute(param) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match) {
    if (match.hd === "hanzi-pyramid" && !match.tl) {
      return /* HanziPyramid */1;
    } else {
      return /* NotFound */2;
    }
  } else {
    return /* Main */0;
  }
}

function getPath(t) {
  switch (t) {
    case /* HanziPyramid */1 :
        return "hanzi-pyramid";
    case /* Main */0 :
    case /* NotFound */2 :
        return "";
    
  }
}

export {
  useRoute ,
  getPath ,
  
}
/* RescriptReactRouter Not a pure module */
