// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  var onClick = Props.onClick;
  var children = Props.children;
  return React.createElement("button", {
              className: "bg-blue-500 hover:bg-blue-700 text-white rounded px-2 py-1",
              onClick: onClick
            }, children);
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
