// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function H1(Props) {
  var children = Props.children;
  return React.createElement("h1", {
              className: "text-4xl"
            }, children);
}

var make = H1;

export {
  make ,
  
}
/* react Not a pure module */
